name: Pytest Test Run

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout from branch
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.0"

    - name: Upgrade & Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt

    - name: Playwright Install
      run: python -m playwright install --with-deps

    - name: Run Tests
      run: pytest